CREATE TABLE "ai-content-extractor_content" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-content-extractor_content_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" varchar(2048) NOT NULL,
	"summary" text,
	"keyPoints" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "ai-content-extractor_content_url_unique" UNIQUE("url")
);
--> statement-breakpoint
CREATE INDEX "url_idx" ON "ai-content-extractor_content" USING btree ("url");